JCN-135-soporte-elasticsearch
janis-commerce/database-dispatcher pull request #3
Opened 2019-08-14 15:34 UTC by Nataniel4

**JCN-135 SOPORTE ELASTICSEARCH**
JCN-135 Agregar soporte para elasticsearch

**LINK AL TICKET**
[https://fizzmod.atlassian.net/browse/JCN-135](https://fizzmod.atlassian.net/browse/JCN-135)

**DESCRIPCIÓN DEL REQUERIMIENTO**
2.1. Se debe agregar al elasticsearch como `DBDriver` soportado

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se aplicaron los cambios solicitados

2019-08-15 20:21 UTC, gastonpereyra commented on README.md
> +- `database [String]` (optional): Database name for connection, example `"myDB"`.
Habría que aclarar que en algunos casos como en **MongoDB** es requerida. O que se fijen en los drivers de cada DDBB si es necesaria.

2019-08-15 21:13 UTC, gastonpereyra approved these changes
Mi único "pero" es que el campo `database` debería seguir siendo requerido aunque ElasticSearch no lo necesite, o que de mínima se explique en el *README*, que según el driver podría llegar a ser necesario.

2019-08-16 21:58 UTC, jormaechea requested changes

2019-08-16 21:58 UTC, jormaechea commented on README.md
> +- `database [String]` (optional): Database name for connection, example `"myDB"`.
Sí, aclararía acá que es requerido para mysql y mongo, pero no para elasticsearch.

2019-08-16 21:58 UTC, jormaechea commented on lib/database-dispatcher.js
> +		if(typeof dbConfig.database !== 'undefined' && typeof dbConfig.database !== 'string')
Acá habría que buscar la manera de validar bien esto. Para mysql y mongo es requerido.
Acepto sugerencias de cómo hacerlo.

2019-08-20 20:44 UTC, gastonpereyra commented on README.md
> +* `database`: Some DBDrivers may require this field, for example, MongoDB and MySQL requires it, but elasticsearch doesn't.
Ya que estas agrega los otros `fields` requeridos

2019-08-20 20:53 UTC, gastonpereyra approved these changes
Listo.

2019-08-21 15:26 UTC, jormaechea approved these changes
Buenísima solución gente! :clap:

2019-08-21 15:29 UTC, merged

2019-08-21 15:29 UTC, jormaechea commented
Publicado en la v1.4.0